# -*- coding: utf-8 -*-
"""House.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DYRmyXaEdsvrILNEO1R_MHMSNLMgs9aU
"""

import pandas as pd
df = pd.read_excel("/content/House.xlsx")
df

import pandas as pd
import matplotlib.pyplot as plt

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_squared_error

data = pd.read_excel("/content/House.xlsx")

data.columns = data.columns.str.strip()

print("Columns:", data.columns.tolist())

X = data.iloc[:, [0]]
y = data.iloc[:, 1]

print(data.head())
print(data.info())
print(data.describe())

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("R2 Score:", r2_score(y_test, y_pred))
print("Mean Squared Error:", mean_squared_error(y_test, y_pred))

X_sorted = X.sort_values(by=X.columns[0])
y_sorted_pred = model.predict(X_sorted)

plt.figure(figsize=(8, 5))

plt.scatter(
    X.iloc[:, 0],
    y,
    color="red",
    label="Original Data"
)

plt.plot(
    X_sorted.iloc[:, 0],
    y_sorted_pred,
    color="blue",
    linewidth=2,
    label="Regression Line"
)

plt.xlabel(X.columns[0])
plt.ylabel(data.columns[1])
plt.title("Linear Regression")
plt.grid(True)
plt.legend()

plt.show()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

data = {
    "StudyHours": [1, 2, 3, 4, 5],
    "Marks": [20, 25, 50, 78, 90]
}

df = pd.DataFrame(data)

X = df[["StudyHours"]]
y = df["Marks"]

poly = PolynomialFeatures(degree=2)

X_poly = poly.fit_transform(X)

model = LinearRegression()
model.fit(X_poly, y)

X_new = np.linspace(1, 5, 100).reshape(-1, 1)
X_new_poly = poly.transform(X_new)
y_new = model.predict(X_new_poly)

plt.figure(figsize=(8,5))

plt.scatter(
    df["StudyHours"],
    df["Marks"],
    color="red",
    s=80,
    label="Original Data"
)

plt.plot(
    X_new,
    y_new,
    color="blue",
    linewidth=3,
    label="Polynomial Curve"
)

plt.xlabel("Study Hours")
plt.ylabel("Marks")
plt.title("Study Hours vs Marks (Polynomial Regression)")
plt.grid(True)
plt.legend()

plt.show()

import pandas as pd
import matplotlib.pyplot as plt

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_squared_error

# Read Excel File
df = pd.read_excel("/content/Exp.xlsx")

# Remove extra spaces from column names
df.columns = df.columns.str.strip()

print(df.head())
print(df.info())
print(df.describe())
print("Columns:", df.columns.tolist())

# Select first column as Experience and second column as Salary
X = df.iloc[:, [0]]
y = df.iloc[:, 1]

# Split the dataset
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=42
)


model = LinearRegression()
model.fit(X_train, y_train)


y_pred = model.predict(X_test)

# Accuracy
print("R2 Score:", r2_score(y_test, y_pred))
print("Mean Squared Error:", mean_squared_error(y_test, y_pred))

# Predict salary for 11 years of experience
experience = pd.DataFrame([[11]], columns=X.columns)
predicted_salary = model.predict(experience)

print("Predicted Salary for 11 Years Experience: ₹", round(predicted_salary[0], 2))

# Regression Line
X_sorted = X.sort_values(by=X.columns[0])
y_sorted = model.predict(X_sorted)

# Plot Graph
plt.figure(figsize=(8,5))

plt.scatter(
    X.iloc[:,0],
    y,
    color="red",
    s=80,
    label="Original Data"
)

plt.plot(
    X_sorted.iloc[:,0],
    y_sorted,
    color="blue",
    linewidth=2,
    label="Regression Line"
)

# Show predicted point
plt.scatter(
    11,
    predicted_salary[0],
    color="green",
    s=120,
    marker="*",
    label="Prediction (11 Years)"
)

plt.text(
    11,
    predicted_salary[0],
    f"₹{predicted_salary[0]:.0f}",
    fontsize=10
)

plt.xlabel(X.columns[0])
plt.ylabel(df.columns[1])
plt.title("Experience vs Salary Prediction")
plt.grid(True)
plt.legend()

plt.show()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures


data = {
    "Experience": [1,2,3,4,5,6,7,8,9,10],
    "Salary": [30000,40000,50000,65000,80000,100000,130000,170000,220000,300000]
}

df = pd.DataFrame(data)

X = df[["Experience"]]
y = df["Salary"]

linear_model = LinearRegression()
linear_model.fit(X, y)

y_linear = linear_model.predict(X)

poly = PolynomialFeatures(degree=2)

X_poly = poly.fit_transform(X)

poly_model = LinearRegression()
poly_model.fit(X_poly, y)

X_new = np.linspace(1, 10, 100).reshape(-1, 1)
X_new_poly = poly.transform(X_new)

y_poly = poly_model.predict(X_new_poly)

plt.figure(figsize=(12,5))

plt.subplot(1,2,1)

plt.scatter(
    df["Experience"],
    df["Salary"],
    color="red",
    label="Original Data"
)

plt.plot(
    df["Experience"],
    y_linear,
    color="yellow",
    linewidth=2,
    label="Linear Regression"
)

plt.xlabel("Experience (Years)")
plt.ylabel("Salary")
plt.title("Linear Regression")
plt.grid(True)
plt.legend()

plt.subplot(1,2,2)

plt.scatter(
    df["Experience"],
    df["Salary"],
    color="green",
    label="Original Data"
)

plt.plot(
    X_new,
    y_poly,
    color="Pink",
    linewidth=2,
    label="Polynomial Regression"
)

plt.xlabel("Experience (Years)")
plt.ylabel("Salary")
plt.title("Polynomial Regression")
plt.grid(True)
plt.legend()

plt.tight_layout()
plt.show()

import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error

data = {
    "Experience": [1,2,3,4,5,6,7,8,9,10],
    "Salary": [3000,3500,4000,4500,5000,5500,6000,6500,7000,7500]
}

df = pd.DataFrame(data)

X = df[["Experience"]]
y = df["Salary"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Actual Salary:", y_test.values)
print("Predicted Salary:", y_pred)
print("R² Score:", r2_score(y_test, y_pred))
print("Mean Squared Error:", mean_squared_error(y_test, y_pred))

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

data = {
    "Experience": [1,2,3,4,5,6,7,8,9,10],
    "Salary": [3000,3500,4000,4500,5000,5500,6000,6500,7000,7500]
}

df = pd.DataFrame(data)

X = df[["Experience"]]
y = df["Salary"]

poly = PolynomialFeatures(degree=3)

X_poly = poly.fit_transform(X)

model = LinearRegression()
model.fit(X_poly, y)

x_range = np.linspace(X.min(), X.max(), 100).reshape(-1,1)
x_range_poly = poly.transform(x_range)

y_curve = model.predict(x_range_poly)

plt.figure(figsize=(8,5))

plt.scatter(X, y, color="blue", s=80, label="Data Points")
plt.plot(x_range, y_curve, color="red", linewidth=3, label="Polynomial Curve")

plt.title("Experience vs Salary")
plt.xlabel("Experience")
plt.ylabel("Salary")
plt.legend()
plt.grid(True)

plt.show()

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.svm import SVR
from sklearn.metrics import r2_score,mean_squared_error

data = pd.DataFrame({
    "Experience":[1,2,3,4,5,6,7,8,9,10],
    "Salary":[30000,35000,45000,50000,65000,80000,100000,130000,170000,220000]

})
data

X=data[["Experience"]]
y=data["Salary"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

model=SVR(kernel="rbf")

model.fit(X,y)

predict=model.predict(X)

print("The future prediction value is:",model.predict([[13]]))

print("R2_Score value is:",r2_score(y,predict))
print("MSE value is:",mean_squared_error(y,predict))

plt.scatter(X,y,color="blue",label="Actual Data")
plt.plot(X,predict,color="red",label="SVR Line")


data

import pandas as pd
import matplotlib.pyplot as plt

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_squared_error
df = pd.read_excel("/content/Ice.xlsx")
df

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.svm import SVR
from sklearn.metrics import r2_score, mean_squared_error

df = pd.read_excel("/content/Ice.xlsx")

X = df.iloc[:, [0]]
y = df.iloc[:, 1]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = SVR(kernel="rbf", C=100, gamma=0.1, epsilon=0.1)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("R² Score:", r2_score(y_test, y_pred))
print("Mean Squared Error:", mean_squared_error(y_test, y_pred))

X_grid = np.arange(min(X.values), max(X.values), 0.01)
X_grid = X_grid.reshape((len(X_grid), 1))

plt.figure(figsize=(8,6))

plt.scatter(X, y, color="blue", s=80, label="Actual Data")
plt.plot(X_grid, model.predict(X_grid), color="red", linewidth=2, label="SVR Curve")

plt.title("Support Vector Regression (SVR)")
plt.xlabel(df.columns[0])
plt.ylabel(df.columns[1])
plt.legend()
plt.grid(True)

plt.show()

